#!/usr/bin/env python3
"""
Packet Wastes AI Player - A Claude-powered MUD bot.

This bot connects to the Packet Wastes MUD via websocket and uses Claude 
to make gameplay decisions. It reports bugs and interacts with other players.
"""

import asyncio
import json
import logging
import os
import random
import re
import string
import sys
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum, auto
from pathlib import Path
from typing import Callable, Optional

from openai import OpenAI
import websockets
from websockets.client import WebSocketClientProtocol

# Reuse the GMCP parser and the tested tutorial instruction parsing.
from mapper import parse_gmcp
from tutorial import extract_command, resolve_model, safe_tutorial_command, _PRAISE

# =============================================================================
# Configuration
# =============================================================================

@dataclass
class BotConfig:
    """Bot configuration - edit these values."""
    # LLM API (ollama via its OpenAI-compatible endpoint)
    api_key: str = "ollama"  # ollama requires a key but ignores its value
    base_url: str = "http://localhost:11434/v1"  # acab-local; override if bot runs off-box
    model: str = "llama3.2"  # set to whatever you've pulled on acab (ollama list)
    
    # Game server
    server_url: str = "wss://74-208-68-248.sslip.io/ws"
    
    # Character details - these get generated by AI if not set
    username: str = ""  # Auto-generated if empty
    password: str = ""  # Auto-generated if empty
    character_name: str = ""  # AI generates this
    race: str = ""  # AI picks this
    character_class: str = ""  # AI picks this
    
    # Timing
    action_interval: float = 4.0  # Seconds between AI decisions
    reconnect_delay: float = 10.0  # Seconds before reconnect attempt
    
    # Logging
    log_level: str = "INFO"
    bug_report_file: str = "bug_reports.jsonl"
    
    # Identity persistence file
    identity_file: str = "bot_identity.json"
    
    @classmethod
    def from_env(cls) -> "BotConfig":
        """Load config from environment variables."""
        config = cls()
        config.api_key = os.getenv("OLLAMA_API_KEY", config.api_key)
        config.base_url = os.getenv("OLLAMA_BASE_URL", config.base_url)
        config.model = os.getenv("MUD_MODEL", config.model)
        config.server_url = os.getenv("MUD_SERVER_URL", config.server_url)
        config.username = os.getenv("MUD_USERNAME", config.username)
        config.password = os.getenv("MUD_PASSWORD", config.password)
        config.character_name = os.getenv("MUD_CHARACTER", config.character_name)
        config.identity_file = os.getenv("MUD_IDENTITY_FILE", config.identity_file)
        config.bug_report_file = os.getenv("MUD_BUG_FILE", config.bug_report_file)
        return config


# =============================================================================
# ANSI Processing
# =============================================================================

class ANSIProcessor:
    """Handles ANSI escape code processing."""
    
    ANSI_PATTERN = re.compile(r'\x1b\[[0-9;]*[mABCDEFGHJKSTfn]|\x1b\].*?\x07')
    
    @classmethod
    def strip(cls, text: str) -> str:
        """Remove ANSI escape codes."""
        return cls.ANSI_PATTERN.sub('', text)
    
    @classmethod
    def extract_colors(cls, text: str) -> list[tuple[str, str]]:
        """Extract text segments with their ANSI codes."""
        # For future use - colored output parsing
        pass


# =============================================================================
# Identity Generator
# =============================================================================

class IdentityGenerator:
    """Generates and persists bot identity using AI."""
    
    # Available races in the game (subset - AI can pick from these)
    RACES = [
        "human", "mutant", "ghoul", "android", "cyborg", "wasteling",
        "dust elf", "sand goblin", "chrome junkie", "rad ghost",
        "salt born", "dust devil", "neon wraith", "bloodkin", "glasskin"
    ]
    
    # Available classes
    CLASSES = [
        "scavenger", "raider", "nomad", "wastelander", "drifter",
        "ruin diver", "scrap weaver", "heatweaver", "chrome hunter",
        "fixer", "gridbound"
    ]
    
    def __init__(self, config: BotConfig):
        self.config = config
        self.identity_file = Path(config.identity_file)
        self.client = OpenAI(api_key=config.api_key, base_url=config.base_url) if config.base_url else None
        self.logger = logging.getLogger("identity")
    
    def load_or_create(self) -> dict:
        """Load existing identity or create a new one."""
        # Try to load existing
        if self.identity_file.exists():
            try:
                with open(self.identity_file) as f:
                    identity = json.load(f)
                self.logger.info(f"Loaded identity: {identity['character_name']}")
                return identity
            except Exception as e:
                self.logger.warning(f"Could not load identity: {e}")
        
        # Generate new identity
        identity = self._generate_identity()
        
        # Save for persistence
        self._save_identity(identity)
        
        return identity
    
    def _generate_identity(self) -> dict:
        """Use AI to generate a unique character identity."""
        # Generate base username (needs to be unique for the account)
        random_suffix = ''.join(random.choices(string.ascii_lowercase + string.digits, k=6))
        username = f"ai_{random_suffix}"
        
        # Generate password
        password = ''.join(random.choices(string.ascii_letters + string.digits + "!@#$", k=16))
        
        if not self.client:
            # No API - use random defaults
            character_name = f"Wanderer{random.randint(100,999)}"
            race = random.choice(self.RACES)
            char_class = random.choice(self.CLASSES)
            backstory = "A mysterious wanderer of the wastes."
        else:
            # Use AI to create identity
            prompt = f"""You are creating a character for a post-apocalyptic MUD game called Packet Wastes.

Generate a unique, memorable character identity. Be creative and interesting.

Available races: {', '.join(self.RACES)}
Available classes: {', '.join(self.CLASSES)}

Respond in this exact JSON format (no other text):
{{
    "character_name": "A single name, 3-12 characters, no spaces, first letter capitalized",
    "race": "one of the available races exactly as written",
    "class": "one of the available classes exactly as written",
    "backstory": "2-3 sentences about who this character is and what drives them"
}}

Be creative! Make this character memorable and unique. The name should fit the post-apocalyptic wasteland setting."""

            try:
                response = self.client.chat.completions.create(
                    model=self.config.model,
                    max_tokens=300,
                    messages=[{"role": "user", "content": prompt}]
                )

                text = response.choices[0].message.content.strip()
                # Extract JSON from response
                json_match = re.search(r'\{[^}]+\}', text, re.DOTALL)
                if json_match:
                    data = json.loads(json_match.group())
                    character_name = data.get("character_name", f"Drifter{random.randint(100,999)}")
                    race = data.get("race", "human")
                    char_class = data.get("class", "scavenger")
                    backstory = data.get("backstory", "A wanderer of the wastes.")
                    
                    # Validate race and class
                    if race.lower() not in [r.lower() for r in self.RACES]:
                        race = random.choice(self.RACES)
                    if char_class.lower() not in [c.lower() for c in self.CLASSES]:
                        char_class = random.choice(self.CLASSES)
                else:
                    raise ValueError("No JSON in response")
                    
            except Exception as e:
                self.logger.warning(f"AI identity generation failed: {e}")
                character_name = f"Drifter{random.randint(100,999)}"
                race = random.choice(self.RACES)
                char_class = random.choice(self.CLASSES)
                backstory = "A mysterious wanderer of the wastes."
        
        # Clean up character name
        character_name = re.sub(r'[^a-zA-Z]', '', character_name)[:12]
        if character_name:
            character_name = character_name[0].upper() + character_name[1:].lower()
        else:
            character_name = f"Wanderer{random.randint(100,999)}"
        
        identity = {
            "username": username,
            "password": password,
            "character_name": character_name,
            "race": race.lower(),
            "class": char_class.lower(),
            "backstory": backstory,
            "created": datetime.now().isoformat(),
        }
        
        self.logger.info(f"Generated new identity: {character_name} the {race} {char_class}")
        self.logger.info(f"Backstory: {backstory}")
        
        return identity
    
    def _save_identity(self, identity: dict) -> None:
        """Save identity to file."""
        try:
            with open(self.identity_file, "w") as f:
                json.dump(identity, f, indent=2)
            self.logger.info(f"Saved identity to {self.identity_file}")
        except Exception as e:
            self.logger.error(f"Could not save identity: {e}")


# =============================================================================
# Game State
# =============================================================================

class ConnectionState(Enum):
    """Connection state machine."""
    DISCONNECTED = auto()
    CONNECTING = auto()
    AWAITING_USERNAME = auto()
    AWAITING_PASSWORD = auto()
    AWAITING_KICK = auto()
    AWAITING_NEW_PASSWORD = auto()
    AWAITING_CONFIRM_PASSWORD = auto()
    AWAITING_CHARACTER_NAME = auto()
    AWAITING_RACE = auto()
    AWAITING_CLASS = auto()
    AWAITING_CONFIRMATION = auto()
    IN_GAME = auto()


@dataclass 
class RoomState:
    """Current room information."""
    name: str = ""
    description: str = ""
    exits: list[str] = field(default_factory=list)
    players: list[str] = field(default_factory=list)
    mobs: list[str] = field(default_factory=list)
    items: list[str] = field(default_factory=list)


@dataclass
class CharacterState:
    """Character stats and status."""
    name: str = ""
    level: int = 1
    health: int = 100
    health_max: int = 100
    mana: int = 100
    mana_max: int = 100
    gold: int = 0
    experience: int = 0
    in_combat: bool = False
    combat_target: str = ""
    inventory: list[str] = field(default_factory=list)
    edibles: list[str] = field(default_factory=list)  # food names currently carried
    equipped: dict[str, str] = field(default_factory=dict)


@dataclass
class GameState:
    """Complete game state."""
    connection: ConnectionState = ConnectionState.DISCONNECTED
    room: RoomState = field(default_factory=RoomState)
    character: CharacterState = field(default_factory=CharacterState)
    message_buffer: list[str] = field(default_factory=list)
    last_command: str = ""
    last_command_time: float = 0.0
    
    def add_message(self, msg: str) -> None:
        """Add message lines to buffer (last 100), dropping GMCP/protocol noise."""
        clean = ANSIProcessor.strip(msg)
        for line in clean.splitlines():
            s = line.strip()
            if not s or s.startswith(('!!GMCP(', '!!MUSIC', 'TEXTMASK')):
                continue
            self.message_buffer.append(s)
        self.message_buffer = self.message_buffer[-100:]
    
    def recent_messages(self, n: int = 20) -> list[str]:
        """Get last n messages."""
        return self.message_buffer[-n:]
    
    def to_context(self) -> str:
        """Generate context string for AI."""
        room = self.room
        char = self.character
        
        return f"""=== CURRENT SITUATION ===
Location: {room.name or 'Unknown'}
{room.description[:300] if room.description else 'No description'}

Exits: {', '.join(room.exits) if room.exits else 'Look around to see exits'}
Players here: {', '.join(room.players) if room.players else 'None visible'}
Creatures here: {', '.join(room.mobs) if room.mobs else 'None visible'}
Items here: {', '.join(room.items) if room.items else 'None visible'}

=== YOUR STATUS ===
Health: {char.health}/{char.health_max} | Mana: {char.mana}/{char.mana_max}
Level: {char.level} | Gold: {char.gold}
Combat: {'Fighting ' + char.combat_target if char.in_combat else 'Not in combat'}
Food in your pack: {', '.join(char.edibles) if char.edibles else 'none'} (to eat, type the exact name, e.g. "eat {char.edibles[0] if char.edibles else 'ration'}")

=== RECENT EVENTS ===
{chr(10).join(self.recent_messages(15))}

=== LAST COMMAND ===
{self.last_command or 'None'}"""


# =============================================================================
# Message Parser
# =============================================================================

class GameParser:
    """Parses game output and updates state."""
    
    # Login flow patterns
    PATTERNS = {
        'username_prompt': re.compile(r'(?:enter your username|username.*?:)', re.I),
        'password_prompt': re.compile(r'(?:enter your password|password:)', re.I),
        'kick_prompt': re.compile(r'(?:already (?:logged in|connected)|kick them)', re.I),
        'new_password': re.compile(r'(?:create a new password|new password)', re.I),
        'confirm_password': re.compile(r'confirm password', re.I),
        'character_name': re.compile(r'(?:enter a name|character name|name for your)', re.I),
        'choose_race': re.compile(r'(?:choose.*race|select.*race|pick.*race)', re.I),
        'choose_class': re.compile(r'(?:choose.*class|select.*class|pick.*class)', re.I),
        'press_enter': re.compile(r'press.*enter', re.I),
        'welcome': re.compile(r'(?:welcome back|you have entered|entering the world)', re.I),
        'game_prompt': re.compile(r'HP:\s*\d+\s*/\s*\d+.*MP:\s*\d+\s*/\s*\d+', re.I),
        
        # Game info patterns
        'exits': re.compile(r'(?:obvious exits?|exits?)[:\s]+([^\n]+)', re.I),
        'health': re.compile(r'(?:HP|Health)[:\s]*(\d+)/(\d+)', re.I),
        'mana': re.compile(r'(?:MP|Mana)[:\s]*(\d+)/(\d+)', re.I),
        'gold': re.compile(r'(?:Gold|Credits)[:\s]*(\d+)', re.I),
        'level': re.compile(r'Level[:\s]*(\d+)', re.I),
        
        # Combat patterns
        'attack_you': re.compile(r'(\w+) (?:attacks?|hits?|strikes?) you', re.I),
        'you_attack': re.compile(r'you (?:attack|hit|strike) (\w+)', re.I),
        'target_dies': re.compile(r'(\w+) (?:is dead|dies|has been slain)', re.I),
        'you_die': re.compile(r'you (?:have died|die|are dead)', re.I),
        
        # Social patterns
        'player_says': re.compile(r'(\w+) says?[,:\s]+["\']?(.+?)["\']?\s*$', re.I),
        'player_tells': re.compile(r'(\w+) tells? you[,:\s]+["\']?(.+?)["\']?\s*$', re.I),
        'player_yells': re.compile(r'(\w+) yells?[,:\s]+["\']?(.+?)["\']?\s*$', re.I),
        'also_here': re.compile(r'(?:also here|you see)[:\s]+([^\n]+)', re.I),
    }
    
    def __init__(self, state: GameState, config: BotConfig):
        self.state = state
        self.config = config
        self.logger = logging.getLogger("parser")
    
    def parse(self, raw: str) -> None:
        """Parse raw game output and update state."""
        text = ANSIProcessor.strip(raw)
        self.state.add_message(text)
        
        # Check login flow
        self._check_login_prompts(text)
        
        # Only parse game info if in-game
        if self.state.connection == ConnectionState.IN_GAME:
            self._parse_room_info(text)
            self._parse_character_info(text)
            self._parse_combat(text)
            self._parse_social(text)
    
    def _check_login_prompts(self, text: str) -> None:
        """Detect and handle login prompts."""
        patterns = self.PATTERNS

        # Once in-game, never reinterpret normal output as login prompts.
        if self.state.connection == ConnectionState.IN_GAME:
            return

        # This MUD has no 'welcome' string; entry is signaled by the status
        # prompt ([... HP:x/y MP:a/b ...]) or by GMCP Char/Room.Info blocks.
        if (patterns['welcome'].search(text)
                or patterns['game_prompt'].search(text)
                or '!!GMCP(Char' in text or '!!GMCP(Room.Info' in text):
            self.state.connection = ConnectionState.IN_GAME
            self.state.character.name = self.config.character_name
            self.logger.info("Successfully entered game")
            return
        
        # A stale session ("User is already connected. Kick them? [y/n]:") must be
        # answered 'y' before login proceeds; otherwise we'd re-send the password
        # and get 'invalid response' forever. Check this before the other prompts.
        if patterns['kick_prompt'].search(text):
            self.state.connection = ConnectionState.AWAITING_KICK
        elif patterns['username_prompt'].search(text):
            self.state.connection = ConnectionState.AWAITING_USERNAME
        elif patterns['new_password'].search(text):
            self.state.connection = ConnectionState.AWAITING_NEW_PASSWORD
        elif patterns['confirm_password'].search(text):
            self.state.connection = ConnectionState.AWAITING_CONFIRM_PASSWORD
        elif patterns['password_prompt'].search(text):
            self.state.connection = ConnectionState.AWAITING_PASSWORD
        elif patterns['character_name'].search(text):
            self.state.connection = ConnectionState.AWAITING_CHARACTER_NAME
        elif patterns['choose_race'].search(text):
            self.state.connection = ConnectionState.AWAITING_RACE
        elif patterns['choose_class'].search(text):
            self.state.connection = ConnectionState.AWAITING_CLASS
        elif patterns['press_enter'].search(text):
            self.state.connection = ConnectionState.AWAITING_CONFIRMATION
    
    def _parse_room_info(self, text: str) -> None:
        """Extract room information."""
        if match := self.PATTERNS['exits'].search(text):
            exits_str = match.group(1).lower()
            self.state.room.exits = [
                e.strip() for e in re.split(r'[,\s]+', exits_str)
                if e.strip() and e.strip() not in ('none', 'and')
            ]
        
        if match := self.PATTERNS['also_here'].search(text):
            names = re.findall(r'\b([A-Z][a-z]+)\b', match.group(1))
            for name in names:
                if name not in self.state.room.players:
                    self.state.room.players.append(name)
    
    def _parse_character_info(self, text: str) -> None:
        """Extract character stats."""
        char = self.state.character
        
        if match := self.PATTERNS['health'].search(text):
            char.health = int(match.group(1))
            char.health_max = int(match.group(2))
        
        if match := self.PATTERNS['mana'].search(text):
            char.mana = int(match.group(1))
            char.mana_max = int(match.group(2))
        
        if match := self.PATTERNS['gold'].search(text):
            char.gold = int(match.group(1))
        
        if match := self.PATTERNS['level'].search(text):
            char.level = int(match.group(1))
    
    def _parse_combat(self, text: str) -> None:
        """Track combat state."""
        char = self.state.character
        
        if match := self.PATTERNS['attack_you'].search(text):
            char.in_combat = True
            char.combat_target = match.group(1)
        
        if match := self.PATTERNS['you_attack'].search(text):
            char.in_combat = True
            char.combat_target = match.group(1)
        
        if self.PATTERNS['target_dies'].search(text) or self.PATTERNS['you_die'].search(text):
            char.in_combat = False
            char.combat_target = ""
    
    def _parse_social(self, text: str) -> None:
        """Track social interactions."""
        for pattern_name in ('player_says', 'player_tells', 'player_yells'):
            if match := self.PATTERNS[pattern_name].search(text):
                speaker = match.group(1)
                if speaker not in self.state.room.players:
                    self.state.room.players.append(speaker)


# =============================================================================
# Bug Reporter
# =============================================================================

class BugReporter:
    """Detects and logs potential game bugs."""
    
    ERROR_PATTERNS = [
        (r"you can'?t do that", "ACTION_BLOCKED"),
        (r"doesn'?t work", "NOT_WORKING"),
        (r"nothing happens", "NO_EFFECT"),
        (r"that doesn'?t seem to work", "NOT_WORKING"),
        (r"error", "ERROR"),
        (r"invalid", "INVALID"),
        (r"not implemented", "NOT_IMPLEMENTED"),
        (r"can'?t buy", "BUY_ISSUE"),
        (r"can'?t sell", "SELL_ISSUE"),
        (r"can'?t mount", "MOUNT_ISSUE"),
        (r"can'?t ride", "MOUNT_ISSUE"),
        (r"can'?t use", "USE_ISSUE"),
        (r"can'?t equip", "EQUIP_ISSUE"),
        (r"doesn'?t exist", "MISSING"),
        (r"not found", "NOT_FOUND"),
        (r"unknown command", "UNKNOWN_CMD"),
        (r"huh\?", "UNKNOWN_CMD"),
        (r"syntax error", "SYNTAX"),
        (r"exception", "EXCEPTION"),
    ]

    # Verbs whose text the server echoes back verbatim (the player's own prose),
    # so an error keyword inside the echo ("...huh?", "...in panic") is a false
    # positive, not a server error.
    SPEECH_VERBS = frozenset({
        "emote", "emot", "pmote", "say", "sayto", "tell", "yell", "shout",
        "gossip", "ooc", "whisper", "think", "describe", "recite", "sing",
    })
    
    def __init__(self, log_file: str):
        self.log_file = Path(log_file)
        self.reported: set[str] = set()
        self.logger = logging.getLogger("bugs")
    
    def check(self, text: str, command: str, room: str) -> Optional[dict]:
        """Check for bug indicators in game output."""
        text_lower = text.lower()
        verb = command.strip().split(" ", 1)[0].lower() if command else ""

        # The server echoes roleplay verbs back verbatim, so any error keyword in
        # the text is the player's own prose, not a server complaint. Skip them.
        if verb in self.SPEECH_VERBS:
            return None
        # Login fumbles (random password attempts at the prompt) aren't game bugs.
        if "invalid login" in text_lower:
            return None

        for pattern, issue_type in self.ERROR_PATTERNS:
            if re.search(pattern, text_lower):
                # Movement refused mid-fight is working-as-intended, not a bug.
                if issue_type == "ACTION_BLOCKED" and "in combat" in text_lower:
                    continue
                key = f"{issue_type}:{command}:{text[:50]}"
                if key not in self.reported:
                    self.reported.add(key)
                    return {
                        "timestamp": datetime.now().isoformat(),
                        "type": issue_type,
                        "command": command,
                        "response": text.strip()[:500],
                        "room": room,
                    }
        return None
    
    def report(self, issue: dict) -> None:
        """Log a bug report."""
        self.logger.warning(f"BUG: {issue['type']} - {issue['command']}")
        with open(self.log_file, "a") as f:
            f.write(json.dumps(issue) + "\n")


# =============================================================================
# AI Brain
# =============================================================================

class AIBrain:
    """Claude-powered decision making."""
    
    SYSTEM_PROMPT_TEMPLATE = """You are {name}, a {race} {char_class} surviving in the post-apocalyptic wasteland.

{backstory}

Just play. Do whatever you want. Explore, fight, talk to people, buy stuff, do quests, cause trouble, make friends, make enemies. You're a real person in this world - act like it.

Stay alive: when you are hungry or starving, eat food from your pack; when thirsty, drink. Rest when badly hurt.

Commands take a real target, never a placeholder. Write the actual name, like "eat jerky strip" or "kill scavenger" -- NEVER type brackets or words like "[food]" or "[item]".
Examples: north  south  east  west  up  down  look  inventory  status  who  quest  help
  eat jerky strip   drink water   kill scavenger   get scrap   drop bone
  buy ration   sell pelt   say hello   tell rover meet me   yell help   emote grins

Reply with ONLY your command. Nothing else."""
    
    def __init__(self, config: BotConfig, identity: dict):
        self.config = config
        self.identity = identity
        self.client = OpenAI(api_key=config.api_key, base_url=config.base_url) if config.base_url else None
        self.logger = logging.getLogger("ai")
        
        # Build personalized system prompt
        self.system_prompt = self.SYSTEM_PROMPT_TEMPLATE.format(
            name=identity.get("character_name", "Wanderer"),
            race=identity.get("race", "human"),
            char_class=identity.get("class", "scavenger"),
            backstory=identity.get("backstory", "A mysterious wanderer."),
        )
    
    def get_login_response(self, state: ConnectionState, config: BotConfig) -> str:
        """Handle login flow without AI."""
        responses = {
            ConnectionState.AWAITING_USERNAME: config.username,
            ConnectionState.AWAITING_PASSWORD: config.password,
            ConnectionState.AWAITING_KICK: "y",
            ConnectionState.AWAITING_NEW_PASSWORD: config.password,
            ConnectionState.AWAITING_CONFIRM_PASSWORD: config.password,
            ConnectionState.AWAITING_CHARACTER_NAME: config.character_name,
            ConnectionState.AWAITING_RACE: config.race,
            ConnectionState.AWAITING_CLASS: config.character_class,
            ConnectionState.AWAITING_CONFIRMATION: "",
        }
        return responses.get(state, "")
    
    def decide(self, game_state: GameState) -> str:
        """Get AI decision for next action."""
        if not self.client:
            self.logger.warning("No API key - defaulting to 'look'")
            return "look"
        
        # Just show what's happening
        context = game_state.to_context()
        prompt = f"{context}\n\nWhat do you do?"
        
        try:
            response = self.client.chat.completions.create(
                model=self.config.model,
                max_tokens=100,
                messages=[
                    {"role": "system", "content": self.system_prompt},
                    {"role": "user", "content": prompt},
                ]
            )

            action = response.choices[0].message.content.strip()
            # Clean up
            action = action.split('\n')[0].strip().strip('"\'`')
            if action.lower().startswith('command:'):
                action = action[8:].strip()
            
            self.logger.debug(f"AI decided: {action}")
            return action
            
        except Exception as e:
            self.logger.error(f"AI error: {e}")
            return "look"


# =============================================================================
# Bot Core
# =============================================================================

class TutorialPilot:
    """Completes the on-rails tutorial deterministically by obeying instructor speech.

    The player bot freeform-plays, which is the wrong behavior inside the tutorial
    (movement is gated and the instructor wants specific commands). While in the
    Tutorial area, the bot defers to this pilot instead of the LLM. Instructions
    arrive as plain-text 'Name says, "..."' lines (with GMCP Comm.Channel as a
    fallback); we parse the command out of them (reusing tutorial.extract_command)
    and feed them back one at a time. Anything the deterministic parser can't
    handle falls back to the local model.
    """

    # NPC/instructor speech on this server: 'Sight Instructor says, "type look."'
    _SAY_RE = re.compile(r'says,\s*["\u201c]([^"\u201d]+)["\u201d]')

    def __init__(self, llm_client=None, model: str = ""):
        self.says: list[str] = []
        self.pointer = 0
        self.last_acted = None
        self.stuck_text = None
        self.stuck_count = 0
        self.last_sent = None
        self.llm = llm_client
        self.model = model

    def ingest(self, message: str) -> None:
        """Collect instructor instructions from a raw server message (called in receive loop).

        This server delivers NPC speech as plain text ('Name says, "..."'), not as
        GMCP Comm.Channel, so plain text is the primary path. The GMCP path is kept
        as a fallback in case a future build emits it.
        """
        clean = ANSIProcessor.strip(message)
        new: list[str] = []
        for text in self._SAY_RE.findall(clean):
            new.append(text.strip())
        for pkg, data in parse_gmcp(message):
            if pkg == "Comm.Channel" and isinstance(data, dict):
                if data.get("source") == "mob" and data.get("text"):
                    new.append(data["text"].strip())
        # This server sometimes emits the same instructor line twice (e.g. the
        # same Comm.Channel back-to-back, or as both plain text and GMCP). Drop a
        # line that just repeats the previous one so it is not acted on twice
        # (which, across a room boundary, would fire a now-invalid second move).
        for t in new:
            if t and (not self.says or self.says[-1] != t):
                self.says.append(t)

    def allow_retry(self) -> None:
        """A move bounced (Room.WrongDir); let the same instruction be re-attempted.

        Clear last_sent too: otherwise the dedup guard (cmd == last_sent -> skip)
        permanently blocks re-issuing the bounced command when the instructor
        repeats the step, and the pilot stalls (e.g. the final 'head west').
        """
        self.last_acted = None
        self.last_sent = None

    def room_changed(self) -> None:
        """We moved to a new room. Clear the command-level dedup so a direction
        can be re-issued in the new room, e.g. two 'west' moves in a row across
        rooms (the fight room's 'head west' then 'the passage west leads on').
        Deliberately keep last_acted: this server emits some instructor lines
        twice, and last_acted still suppresses a duplicate of the SAME text so it
        does not fire a second, now-invalid move just after we crossed a boundary.
        """
        self.last_sent = None
        self.stuck_text = None
        self.stuck_count = 0

    def next_command(self) -> Optional[str]:
        """Next deterministic tutorial command to send, or None if nothing to do now."""
        while self.pointer < len(self.says):
            text = self.says[self.pointer]
            self.pointer += 1

            if _PRAISE.search(text):
                self.last_acted = None
                self.last_sent = None
                self.stuck_text = None
                self.stuck_count = 0
                continue
            if text == self.last_acted:
                continue

            cmd = extract_command(text)
            if cmd is None and self.llm:
                cmd = self._llm_command(text)
            if cmd:
                self.last_acted = text
                self.stuck_text = None
                self.stuck_count = 0
                if cmd == self.last_sent:
                    continue  # same command again with no progress since; skip
                self.last_sent = cmd
                return cmd

            # One-off flavor lines flow past; only count a repeating instruction.
            if text == self.stuck_text:
                self.stuck_count += 1
            else:
                self.stuck_text = text
                self.stuck_count = 1
        return None

    def _llm_command(self, text: str) -> Optional[str]:
        try:
            resp = self.llm.chat.completions.create(
                model=self.model, max_tokens=20,
                messages=[{"role": "user", "content": (
                    "You are completing a MUD tutorial. An instructor said:\n"
                    f'"{text}"\n'
                    "If it tells you to type a specific command or move a "
                    "direction, reply with ONLY that command (e.g. 'look' or "
                    "'west'). If it is just flavor, praise, or encouragement with "
                    "no specific command to type, reply with exactly: NONE"
                )}],
            )
            cmd = resp.choices[0].message.content.strip().splitlines()[0]
            if cmd.strip().strip("\"'`.").upper() == "NONE":
                return None
            return safe_tutorial_command(cmd)
        except Exception:
            return None


# Brute-force escape order for a buggy tutorial gate. When the instructor directs
# an exit the server then refuses (Room.WrongDir on the final 'head west' here),
# we stop trusting the instruction and just try to leave by ANY door. Compass dirs
# first (most likely to be real), then generic "get me out" verbs as a last gasp.
_ALL_DIRS = [
    "north", "south", "east", "west", "up", "down",
    "northeast", "northwest", "southeast", "southwest",
    "n", "s", "e", "w", "u", "d", "ne", "nw", "se", "sw",
]
_ESCAPE_VERBS = ["out", "leave", "exit", "enter", "continue", "go"]

# The 'Learning to Survive' lesson gates its exit on survival skills, but only
# teaches drink/eat/forage explicitly; it ALSO silently requires `search` (the
# only confirmed unlock, found by probing) before it stops saying "Not yet!
# Survival skills first." Cycle through these on a gate refusal so `search`
# always gets issued.
_SURVIVAL_SKILLS = ["search", "forage", "drink water", "eat ration"]


class MUDBot:
    """Main bot controller."""
    
    def __init__(self, config: BotConfig):
        self.config = config
        self.logger = logging.getLogger("bot")

        # Resolve the model name against what the server actually has BEFORE any
        # LLM use (identity generation, tutorial, open-world play). ollama tags
        # carry a quant suffix, so a friendly name like 'qwen3:...-2507' 404s on
        # every call and silently degrades the bot to canned "look" forever.
        if config.base_url:
            probe = OpenAI(api_key=config.api_key, base_url=config.base_url)
            config.model = resolve_model(probe, config.model, self.logger)
            self.logger.info(f"Using model: {config.model}")

        # Generate or load identity
        self.identity_gen = IdentityGenerator(config)
        self.identity = self.identity_gen.load_or_create()
        
        # Apply identity to config for login
        self.config.username = self.identity["username"]
        self.config.password = self.identity["password"]
        self.config.character_name = self.identity["character_name"]
        self.config.race = self.identity["race"]
        self.config.character_class = self.identity["class"]
        
        self.logger.info(f"Playing as: {self.config.character_name} the {self.config.race} {self.config.character_class}")
        
        self.state = GameState()
        self.parser = GameParser(self.state, config)
        self.brain = AIBrain(config, self.identity)
        self.bugs = BugReporter(config.bug_report_file)
        self.ws: Optional[WebSocketClientProtocol] = None
        self.running = False

        # Tutorial handling: deferred to a deterministic pilot while in the
        # Tutorial area; the LLM takes over once we're out in the open world.
        self.area: Optional[str] = None
        # Deterministic-only tutorial: the instructor's "type X"/"head X"/
        # "passage <dir>" lines are fully parseable. The LLM is intentionally NOT
        # wired in here: the look lesson is full of flavor like "there is an exit
        # to the east" that precedes the real "type look east", and a model turns
        # that flavor into wrong moves. The deterministic parser returns None for
        # such lines, so they correctly flow past instead of triggering a move.
        self.tutorial = TutorialPilot(llm_client=None, model=config.model)
        self._wrongdir = False
        self._tutorial_idle = 0
        self._wrongdir_cmd: Optional[str] = None   # last move that bounced (Room.WrongDir)
        self._wrongdir_n = 0                        # consecutive bounces of that move
        self._dead_moves: set[str] = set()          # moves proven rejected; stop re-sending
        # Edible item names (lowercased) seen in GMCP inventory. The LLM tends to
        # say "use <food>", which the server rejects ("You can't use ..."); we
        # rewrite to "eat <food>" so the bot actually feeds itself. See _track_edibles.
        self._edible_items: set[str] = set()
        # Escape sweep: when the instructed exit is a dead no-op, brute-force our
        # way out of the tutorial by trying every other direction in turn.
        self._room_num: Optional[int] = None        # current GMCP room id (for move detection)
        self._room_exits: list[str] = []            # directions the current room claims to have
        self._room_exit_map: dict[str, int] = {}    # direction -> destination room id
        self._tutorial_visited: set[int] = set()    # tutorial rooms already entered
        self._escaping = False                      # currently brute-forcing an exit
        self._escape_queue: Optional[list[str]] = None  # directions left to try
        self._escape_exhausted = False              # tried every direction, all rejected
        # Walking out when a lesson ends without a move instruction (survival
        # training just stops talking). Gated on instructor silence so it never
        # fires mid-lesson; a speculative move that bounces backs off gently
        # instead of escalating to the brute-force escape sweep.
        self._progress_move: Optional[str] = None   # last speculative "walk out" move
        self._last_say_count = 0                    # instructor lines seen at last check
        self._silent_ticks = 0                      # idle ticks with no new instructor speech
        # Skill-gated lessons: the survival lesson won't let you leave until you
        # forage SUCCESSFULLY ("not every attempt succeeds, but persistence pays
        # off"), and a premature move is refused with "Not yet! Survival skills
        # first." A single forage isn't enough, so when we see that refusal we
        # re-issue the lesson's skill command (forage) until it takes.
        self._skill_retry_pending = False           # saw a "finish the lesson first" refusal
        self._skill_retries = 0                     # how many times we've re-tried the skill here
        self._last_skill_cmd: Optional[str] = None  # last non-move tutorial command (e.g. 'forage')

    async def connect(self) -> bool:
        """Establish websocket connection."""
        self.logger.info(f"Connecting to {self.config.server_url}")
        try:
            self.ws = await websockets.connect(
                self.config.server_url,
                ping_interval=30,
                ping_timeout=10,
            )
            self.state.connection = ConnectionState.CONNECTING
            self.logger.info("Connected!")
            return True
        except Exception as e:
            self.logger.error(f"Connection failed: {e}")
            return False
    
    def _track_edibles(self, char: dict) -> None:
        """Record names of edible items from a GMCP Char inventory block so we can
        feed the character with the right verb AND show the brain what it can eat.
        Food shows up as type 'food' or 'botanical', or subtype 'edible'. The GMCP
        Char block is a full snapshot, so the current list is rebuilt each time
        (deduped) while _edible_items stays cumulative for command rewriting."""
        backpack = (((char.get("Inventory") or {}).get("Backpack")) or {})
        current: list[str] = []
        seen: set[str] = set()
        for item in backpack.get("items", []):
            if not isinstance(item, dict):
                continue
            name = str(item.get("name", "")).strip()
            if not name:
                continue
            if item.get("type") in ("food", "botanical") or item.get("subtype") == "edible":
                low = name.lower()
                self._edible_items.add(low)
                if low not in seen:
                    seen.add(low)
                    current.append(name)  # keep original case for the eat command
        # Surface the current edibles to the brain (via to_context) so it issues
        # 'eat jerky strip' instead of inventing the literal 'eat [food]'.
        self.state.character.edibles = current

    def _rewrite_command(self, command: str) -> str:
        """The LLM often says 'use <food>', which the server rejects. Rewrite it
        to 'eat <food>' when the target is a known edible item."""
        parts = command.strip().split(" ", 1)
        if len(parts) == 2 and parts[0].lower() == "use":
            target = parts[1].strip().lower()
            if target in self._edible_items or any(
                target in name or name in target for name in self._edible_items
            ):
                fixed = f"eat {parts[1].strip()}"
                self.logger.info(f"Rewrote '{command}' -> '{fixed}' (edible item)")
                return fixed
        return command

    async def send(self, command: str) -> None:
        """Send command to game."""
        if not self.ws:
            return

        command = self._rewrite_command(command)
        self.state.last_command = command
        self.state.last_command_time = asyncio.get_event_loop().time()
        
        self.logger.info(f">>> {command}")
        await self.ws.send(command)
    
    async def receive_loop(self) -> None:
        """Handle incoming messages."""
        if not self.ws:
            return
        
        try:
            async for message in self.ws:
                if isinstance(message, bytes):
                    message = message.decode('utf-8', errors='replace')
                
                # Print to console (with colors)
                print(message, end='', flush=True)
                
                # Parse
                self.parser.parse(message)

                # Track current area + tutorial instructions from GMCP.
                for pkg, data in parse_gmcp(message):
                    if pkg == "Room.Info" and isinstance(data, dict):
                        self.area = data.get("area", self.area)
                        num = data.get("num")
                        if num is not None and num != self._room_num:
                            self._on_room_change(num, data)
                    elif pkg == "Char" and isinstance(data, dict):
                        self._track_edibles(data)
                if "!!GMCP(Room.WrongDir" in message:
                    self._wrongdir = True
                self.tutorial.ingest(message)

                # Check for bugs
                clean = ANSIProcessor.strip(message)
                # Skill-gated lesson refusal: the instructor blocks the exit until
                # the current skill (foraging) is actually completed. Re-try the
                # skill rather than treating the exit as a dead end.
                if self.area and self.area.lower() == "tutorial":
                    low = clean.lower()
                    if "skills first" in low or "not yet" in low:
                        self._skill_retry_pending = True
                if issue := self.bugs.check(clean, self.state.last_command, self.state.room.name):
                    self.bugs.report(issue)
                    
        except websockets.ConnectionClosed:
            self.logger.warning("Connection closed")
            self.state.connection = ConnectionState.DISCONNECTED
        except Exception as e:
            self.logger.error(f"Receive error: {e}")
            self.state.connection = ConnectionState.DISCONNECTED
    
    def _on_room_change(self, num: int, data: dict) -> None:
        """A new Room.Info room id arrived. If we actually moved, a brute-force
        escape attempt worked (or the instructor moved us) — drop the stale
        rejection state and go back to obeying the instructor in the new room.
        """
        moved = self._room_num is not None and num != self._room_num
        self._room_num = num
        exits = data.get("exits") or {}
        self._room_exits = [d.lower() for d in exits.keys()]
        self._room_exit_map = {
            str(d).lower(): n for d, n in exits.items() if isinstance(n, int)
        }
        self._tutorial_visited.add(num)
        if moved:
            if self._escaping:
                self.logger.info(
                    f"Escaped! A brute-forced move landed us in room {num}. "
                    "Resuming the instructor's tutorial here."
                )
            self._escaping = False
            self._escape_queue = None
            self._dead_moves.clear()      # rejections were for the old room
            self._wrongdir_cmd, self._wrongdir_n = None, 0
            self._progress_move = None    # speculative walk-out succeeded / moot
            self._silent_ticks = 0        # fresh room, fresh instructor
            self._skill_retry_pending = False  # gate state belonged to the old room
            self._skill_retries = 0
            self._last_skill_cmd = None
            # Let the pilot re-issue a direction it just used; a new room's
            # instruction may legitimately repeat the previous move.
            self.tutorial.room_changed()

    def _tutorial_progress_move(self) -> Optional[str]:
        """Pick an advertised exit toward a room we have not visited, for when the
        instructor's scripted lesson ends without telling us where to go. Only
        returns unvisited destinations, so it walks forward (and eventually out of
        the Tutorial) without oscillating back through finished lessons. Returns
        None if every exit leads somewhere already seen (or there are none)."""
        for direction, dest in self._room_exit_map.items():
            if direction in self._dead_moves:
                continue
            if dest not in self._tutorial_visited:
                return direction
        return None

    def _begin_escape(self, bounced: Optional[str]) -> None:
        """The instructed exit is a confirmed no-op. Build a brute-force sweep of
        every other direction (room-advertised exits first), skipping ones already
        proven dead, and start trying them."""
        if self._escaping:
            return
        self._escaping = True
        self._escape_exhausted = False
        order: list[str] = []
        for d in self._room_exits + _ALL_DIRS + _ESCAPE_VERBS:
            d = d.lower()
            if d not in order:
                order.append(d)
        self._escape_queue = [d for d in order if d not in self._dead_moves]
        self.logger.warning(
            f"Instructed exit {bounced!r} is a dead no-op (buggy MUD). "
            f"Brute-forcing an exit; will try in order: {self._escape_queue}"
        )

    def _next_escape_move(self) -> Optional[str]:
        """Pop the next untried escape direction, or None if the sweep is spent."""
        if not self._escaping:
            return None
        while self._escape_queue:
            d = self._escape_queue.pop(0)
            if d not in self._dead_moves:
                return d
        # Swept every direction and the server refused them all.
        if not self._escape_exhausted:
            self._escape_exhausted = True
            self.logger.error(
                "Brute-force escape exhausted: every direction was rejected. The "
                "tutorial gate is genuinely sealed on this build; idling."
            )
        return None

    async def action_loop(self) -> None:
        """Main decision loop."""
        await asyncio.sleep(2)  # Wait for initial prompts
        self._login_sent_for = None  # which login prompt-state we've already answered

        while self.running and self.state.connection != ConnectionState.DISCONNECTED:
            try:
                # Rate limit
                now = asyncio.get_event_loop().time()
                elapsed = now - self.state.last_command_time
                if elapsed < self.config.action_interval:
                    await asyncio.sleep(self.config.action_interval - elapsed)
                
                # Get action
                conn_state = self.state.connection
                
                if conn_state == ConnectionState.IN_GAME:
                    if self.area and self.area.lower() == "tutorial":
                        # On rails: obey the instructor, don't freeform.
                        if self._skill_retry_pending and self._skill_retries < 12:
                            # The exit is gated on finishing a skill lesson (the
                            # survival room won't release you until you've also
                            # `search`ed, which it never tells you to do). The
                            # refusal is "complete the lesson," not "dead exit," so
                            # clear the bounce and cycle through the survival skills
                            # (search first) instead of marking the door dead and
                            # stalling on 'look'.
                            self._skill_retry_pending = False
                            self._wrongdir = False
                            action = _SURVIVAL_SKILLS[self._skill_retries % len(_SURVIVAL_SKILLS)]
                            self._skill_retries += 1
                        elif self._wrongdir:
                            self._wrongdir = False
                            bounced = self.state.last_command
                            self.tutorial.allow_retry()
                            if bounced and bounced == self._progress_move:
                                # A speculative "walk out" guess hit a still-locked
                                # exit. Don't escalate to the escape sweep: mark
                                # this exit dead so we try a different one, and wait
                                # for the instructor (the lesson isn't done yet).
                                self._dead_moves.add(bounced)
                                self._progress_move = None
                                action = None
                            elif self._escaping:
                                # Mid brute-force: this direction is just another
                                # locked door. Mark it dead and try the next one.
                                if bounced:
                                    self._dead_moves.add(bounced)
                                action = self._next_escape_move()
                            else:
                                if bounced == self._wrongdir_cmd:
                                    self._wrongdir_n += 1
                                else:
                                    self._wrongdir_cmd, self._wrongdir_n = bounced, 1
                                if bounced and bounced not in self._dead_moves and self._wrongdir_n <= 2:
                                    # Transient lock (e.g. just-ended combat): retry once or twice.
                                    action = bounced
                                else:
                                    # Persistently rejected though the tutorial instructed it
                                    # (the final 'head west' is a no-op on this build). Report
                                    # it once — finding this is the bot's job — then stop
                                    # trusting the instruction and brute-force an exit.
                                    if bounced and bounced not in self._dead_moves:
                                        self._dead_moves.add(bounced)
                                        self.bugs.report({
                                            "timestamp": datetime.now().isoformat(),
                                            "type": "EXIT_WRONGDIR",
                                            "command": bounced,
                                            "response": (f"Server rejected '{bounced}' (Room.WrongDir) repeatedly "
                                                         "though the tutorial directed it; tutorial cannot complete."),
                                            "room": self.state.room.name,
                                        })
                                        self.logger.warning(
                                            f"Tutorial instruction '{bounced}' bounces (Room.WrongDir). "
                                            "Server-side MUD bug; logged. Ignoring the instructor and "
                                            "trying every other direction to escape the tutorial."
                                        )
                                    self._begin_escape(bounced)
                                    action = self._next_escape_move()
                        elif self._escaping:
                            # No bounce this tick but still sweeping: a prior escape
                            # move was silently eaten (no move, no WrongDir). Try the
                            # next direction.
                            action = self._next_escape_move()
                        else:
                            action = self.tutorial.next_command()
                            if action is not None:
                                self._progress_move = None  # a real instruction, not speculative
                                # Remember the lesson's skill verb (forage/drink/eat,
                                # not a movement) so a "skills first" gate can re-try it.
                                if action.split()[0].lower() not in _ALL_DIRS and action != "look":
                                    self._last_skill_cmd = action
                        # Never re-issue a move we've already proven the server rejects.
                        if action in self._dead_moves:
                            action = None
                        if action is None:
                            self._tutorial_idle += 1
                            # Track instructor silence: a lesson that is still in
                            # progress keeps emitting new lines, so only treat the
                            # lesson as "over" once no NEW instructor speech has
                            # arrived for a sustained stretch (not just a mid-step
                            # pause between "drink water" and "eat ration").
                            if len(self.tutorial.says) != self._last_say_count:
                                self._last_say_count = len(self.tutorial.says)
                                self._silent_ticks = 0
                            else:
                                self._silent_ticks += 1
                            # A scripted lesson can end without an explicit
                            # "head <dir>" (survival training just stops talking).
                            # Once the instructor has gone quiet, walk an advertised
                            # exit toward an unvisited room to progress out.
                            if self._silent_ticks >= 12 and not self._escaping:
                                mv = self._tutorial_progress_move()
                                if mv:
                                    action = mv
                                    self._progress_move = mv
                                    self._silent_ticks = 0
                                    self._tutorial_idle = 0
                            if action is None and self._tutorial_idle >= 6:
                                self._tutorial_idle = 0
                                action = "look"
                        else:
                            self._tutorial_idle = 0
                    else:
                        # Open world: let the LLM play freely.
                        action = self.brain.decide(self.state)
                elif conn_state != ConnectionState.DISCONNECTED:
                    # Handle login flow — answer each prompt-state exactly once so a
                    # response (e.g. 'y' to a kick prompt) can't be re-sent and leak
                    # into the game as a command before the state advances.
                    if conn_state == self._login_sent_for:
                        action = None
                    else:
                        action = self.brain.get_login_response(conn_state, self.config)
                        self._login_sent_for = conn_state
                else:
                    break
                
                if action is not None:
                    await self.send(action)
                
                await asyncio.sleep(0.5)
                
            except Exception as e:
                self.logger.error(f"Action loop error: {e}")
                await asyncio.sleep(2)
    
    async def run(self) -> None:
        """Main entry point."""
        self.logger.info("=" * 50)
        self.logger.info("PACKET WASTES AI BOT")
        self.logger.info("=" * 50)
        self.logger.info(f"Character: {self.config.character_name}")
        self.logger.info(f"Server: {self.config.server_url}")
        self.logger.info(f"Bug reports: {self.config.bug_report_file}")
        
        if not self.config.base_url:
            self.logger.warning("No base_url set - bot will only do login flow")
        
        while True:
            if not await self.connect():
                self.logger.info(f"Retrying in {self.config.reconnect_delay}s...")
                await asyncio.sleep(self.config.reconnect_delay)
                continue
            
            self.running = True
            
            try:
                await asyncio.gather(
                    self.receive_loop(),
                    self.action_loop(),
                )
            except KeyboardInterrupt:
                self.logger.info("Shutting down...")
                break
            finally:
                self.running = False
                if self.ws:
                    await self.ws.close()
            
            self.logger.info(f"Reconnecting in {self.config.reconnect_delay}s...")
            await asyncio.sleep(self.config.reconnect_delay)


# =============================================================================
# Entry Point
# =============================================================================

def setup_logging(level: str = "INFO") -> None:
    """Configure logging."""
    logging.basicConfig(
        level=getattr(logging, level.upper()),
        format='[%(asctime)s] [%(name)s] %(levelname)s: %(message)s',
        datefmt='%H:%M:%S',
    )


def main() -> None:
    """Main entry point."""
    config = BotConfig.from_env()
    setup_logging(config.log_level)
    
    print("""
╔══════════════════════════════════════════════════════════════╗
║            PACKET WASTES AI PLAYER                           ║
║                                                              ║
║  An AI-powered bot that explores, fights, and socializes.    ║
║  Reports bugs and issues to bug_reports.jsonl                ║
║                                                              ║
║  Runs against ollama (OLLAMA_BASE_URL / MUD_MODEL to config)  ║
║  Press Ctrl+C to stop                                        ║
╚══════════════════════════════════════════════════════════════╝
""")
    
    bot = MUDBot(config)
    
    try:
        asyncio.run(bot.run())
    except KeyboardInterrupt:
        print("\nGoodbye!")


if __name__ == "__main__":
    main()
